#!/usr/bin/env bash
#404 error not found customized

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html
replaced_string="server_name _;\n\trewrite ^\/redirect_me Location: https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;"
sudo sed -i "s/server_name _;/$replaced_string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
replaced_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html; \n\t\tinternal;\n\t}" 
sudo sed -i "s/listen 80 default_server;/$replaced_string/" /etc/nginx/sites-available/default 

sudo service nginx restart
