#!/usr/bin/bash
#customised HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#error checking and reloading
sudo nginx -t
sudo service nginx reload
