#!/usr/bin/env bash
#checking for updates and installing them
sudo apt-get update
sudo apt-get install -y nginx

#index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

#redirection
replaced_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$replaced_string/" /etc/nginx/sites-enabled/default

#custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
replaced_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$replaced_string/" /etc/nginx/sites-enabled/default

#customised HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#error checking and reloading
sudo nginx -t
sudo service nginx reload
