#!/usr/bin/env bash
# a script that displays numbers from 1 to 100. Displays FizzBuzz when the number is a multiple of 3 and 5. Displays Fizz when the number is multiple of 3. Displays Buzz when the number is a multiple of 5, Otherwise, displays the number in a list format
for ((o=1; o <= 100; o++))
do
	if (( o % 5 == 0  &&  o % 3 == 0 ))
	then
		echo "FizzBuzz"
	elif (( o % 3 == 0 )) 
	then
		echo "Fizz"
	elif (( o % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$o"
	fi
done
